import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ACMANI VAULTs",
  description: "ACMANI VAULTs Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="jp">
      <body className={"APP_BODY"} style={{margin:"none", backgroundColor:"#0008"}}>
        {children}
      </body>
    </html>
  );
}
