# Generated by Django 5.1.5 on 2025-01-21 16:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("model", models.IntegerField(default=0)),
                ("thickness", models.IntegerField(default=0)),
                ("theme", models.IntegerField(default=0)),
                ("species", models.TextField(default="")),
                ("species_details", models.TextField(default="")),
                ("traits", models.TextField(default="")),
                ("traits_details", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("theme", models.IntegerField(default=0)),
                ("hair", models.TextField(default="")),
                ("eyes", models.TextField(default="")),
                ("outfits_main", models.TextField(default="")),
                ("outfits_sub", models.TextField(default="")),
                ("equips_main", models.TextField(default="")),
                ("equips_sub", models.TextField(default="")),
                ("skin_main", models.TextField(default="")),
                ("skin_sub", models.TextField(default="")),
                ("nipples", models.TextField(default="")),
                ("genitals", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Constants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.TextField(default="")),
                ("is_lewd", models.BooleanField(default=None)),
                ("name", models.TextField(default="")),
                ("value", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Faces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("looks", models.IntegerField(default=0)),
                ("eyes", models.IntegerField(default=0)),
                ("personality", models.IntegerField(default=0)),
                ("moods", models.IntegerField(default=0)),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Figures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("thickness", models.IntegerField(default=0)),
                ("boobs", models.IntegerField(default=0)),
                ("bodies", models.IntegerField(default=0)),
                ("butts", models.IntegerField(default=0)),
                ("skin_details", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Hairs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("hair_style", models.TextField(default="")),
                ("bangs_style", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("weathers", models.IntegerField(default=0)),
                ("periods", models.IntegerField(default=0)),
                ("times", models.IntegerField(default=0)),
                ("locations_details", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Lowers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("model", models.IntegerField(default=0)),
                ("public", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("sheath", models.IntegerField(default=0)),
                ("foreskin", models.IntegerField(default=0)),
                ("genital_details", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Outfits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("jobs", models.TextField(default="")),
                ("jobs_details", models.TextField(default="")),
                ("outfits_details", models.TextField(default="")),
                ("equips_details", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Phrases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("header", models.TextField(default="")),
                ("footer", models.TextField(default="")),
                ("negative", models.TextField(default="")),
                ("request_order", models.TextField(default="")),
                ("playing_order", models.TextField(default="")),
                ("posting_desc", models.TextField(default="")),
                ("content_desc", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("story", models.TextField(default="")),
                ("title_JP", models.TextField(default="")),
                ("title_EN", models.TextField(default="")),
                ("title_symbol", models.TextField(default="")),
                ("picture_count", models.TextField(default="")),
                ("wallpaper_count", models.TextField(default="")),
                ("picture_URL", models.TextField(default="")),
                ("wallpaper_URL", models.TextField(default="")),
                (
                    "notes",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Prompts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("HEADER", models.TextField(default="")),
                ("basis", models.TextField(default="")),
                ("faces", models.TextField(default="")),
                ("hairs", models.TextField(default="")),
                ("figures", models.TextField(default="")),
                ("location", models.TextField(default="")),
                ("outfits", models.TextField(default="")),
                ("equips", models.TextField(default="")),
                ("emotes", models.TextField(default="")),
                ("fluids", models.TextField(default="")),
                ("upper", models.TextField(default="")),
                ("lower", models.TextField(default="")),
                ("actions", models.TextField(default="")),
                ("posing", models.TextField(default="")),
                ("additional", models.TextField(default="")),
                ("FOOTER", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("group_id", models.IntegerField(default=0)),
                ("index", models.IntegerField(default=0)),
                ("name", models.TextField(default="")),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Uppers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.IntegerField(default=0)),
                ("inverted", models.IntegerField(default=0)),
                ("puffy", models.IntegerField(default=0)),
                ("areola", models.IntegerField(default=0)),
                ("nipples", models.IntegerField(default=0)),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="Weights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
                (
                    "theme",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
                (
                    "weathers",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
                (
                    "periods",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
                (
                    "angles",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
                (
                    "directions",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
                (
                    "focuses",
                    models.JSONField(
                        default=list, validators=[app.models.BaseModelClass.valid_list]
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "abstract": False,},
        ),
    ]
