# Generated by Django 5.1.5 on 2025-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_basis_options_alter_colors_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basis", name="Model", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="basis", name="Theme", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="basis", name="Thickness", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="basis", name="request_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="colors", name="Theme", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="colors",
            name="request_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="faces", name="Eyes", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="faces", name="Looks", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="faces", name="Moods", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="faces",
            name="Personality",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="faces", name="request_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="figures", name="Bodies", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="figures", name="Boobs", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="figures", name="Butts", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="figures",
            name="Thickness",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="figures",
            name="request_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="hairs", name="Size", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="hairs", name="request_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location", name="Periods", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location", name="Times", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="Weathers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="request_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lowers", name="Foreskin", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lowers", name="Model", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lowers", name="Public", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lowers", name="Sheath", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lowers", name="Size", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lowers",
            name="request_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="outfits",
            name="request_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posts", name="task_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prompts", name="task_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="requests", name="task_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task", name="group_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task", name="index", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uppers", name="Areola", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uppers", name="Inverted", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uppers", name="Nipples", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uppers", name="Puffy", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uppers",
            name="request_id",
            field=models.IntegerField(default=0),
        ),
    ]
